# Generated by Django 2.2.3 on 2020-04-12 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, default='Default title', max_length=200, verbose_name='название рус.')),
                ('title_en', models.CharField(blank=True, default='Default title', max_length=200, verbose_name='название анл.')),
                ('title_jp', models.CharField(blank=True, default='Default title', max_length=200, verbose_name='название япн.')),
                ('image', models.URLField(blank=True, verbose_name='изображение')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='pokemon_entities.Pokemon', verbose_name='эволюция')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='появился в')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='исчез в')),
                ('level', models.IntegerField(null=True, verbose_name='уровень')),
                ('health', models.IntegerField(null=True, verbose_name='здоровье')),
                ('attack', models.IntegerField(null=True, verbose_name='атака')),
                ('defence', models.IntegerField(null=True, verbose_name='защита')),
                ('stamina', models.IntegerField(null=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='связи')),
            ],
        ),
    ]
