# Generated by Django 2.2.3 on 2020-04-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20200406_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.URLField(),
        ),
    ]
